export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userConstants = {
    GET_PROFILE_REQUEST: 'GET_PROFILE_REQUEST',
    GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
    GET_PROFILE_FAILURE: 'GET_PROFILE_REQUEST',
}

export const facultyConstants = {
    GET_FACULTY_REQUEST: 'GET_FACULTY_REQUEST',
    GET_FACULTY_SUCCESS: 'GET_FACULTY_SUCCESS',
    GET_FACULTY_FAILURE: 'GET_FACULTY_FAILURE',
    ADD_FACULTY_REQUEST: 'ADD_FACULTY_REQUEST',
    ADD_FACULTY_SUCCESS: 'ADD_FACULTY_SUCCESS',
    ADD_FACULTY_FAILURE: 'ADD_FACULTY_FAILURE',
}