export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userConstants = {
    GET_USERS_REQUEST: 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_FAILURE: 'GET_USERS_FAILURE',
    UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
}

export const chatConstants = {
    GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_FAILURE: 'GET_MESSAGES_REQUEST',
    GET_MESSAGE_AFTER_SEND: 'GET_MESSAGE_AFTER_SEND'
}

export const contributionConstants = {
    GET_ALL_CONTRIBUTION_REQUEST: 'GET_ALL_CONTRIBUTION_REQUEST',
    GET_ALL_CONTRIBUTION_SUCCESS: 'GET_ALL_CONTRIBUTION_SUCCESS',
    GET_ALL_CONTRIBUTION_FAILURE: 'GET_ALL_CONTRIBUTION_FAILURE',
    GET_PUBLIC_CONTRIBUTION_REQUEST: 'GET_PUBLIC_CONTRIBUTION_REQUEST',
    GET_PUBLIC_CONTRIBUTION_SUCCESS: 'GET_PUBLIC_CONTRIBUTION_SUCCESS',
    GET_PUBLIC_CONTRIBUTION_FAILURE: 'GET_PUBLIC_CONTRIBUTION_FAILURE',
    GET_CONTRIBUTION_BY_FACULTY_REQUEST: 'GET_CONTRIBUTION_BY_FACULTY_REQUEST',
    GET_CONTRIBUTION_BY_FACULTY_SUCCESS: 'GET_CONTRIBUTION_BY_FACULTY_SUCCESS',
    GET_CONTRIBUTION_BY_FACULTY_FAILURE: 'GET_CONTRIBUTION_BY_FACULTY_FAILURE',
    PUBLISH_CONTRIBUTION_REQUEST: 'PUBLISH_CONTRIBUTION_REQUEST',
    PUBLISH_CONTRIBUTION_SUCCESS: 'PUBLISH_CONTRIBUTION_SUCCESS',
    PUBLISH_CONTRIBUTION_FAILURE: 'PUBLISH_CONTRIBUTION_FAILURE',
    ADD_CONTRIBUTION_REQUEST: 'ADD_CONTRIBUTION_REQUEST',
    ADD_CONTRIBUTION_SUCCESS: 'ADD_CONTRIBUTION_SUCCESS',
    ADD_CONTRIBUTION_FAILURE: 'ADD_CONTRIBUTION_FAILURE',
    UPDATE_CONTRIBUTION_REQUEST: 'UPDATE_CONTRIBUTION_REQUEST',
    UPDATE_CONTRIBUTION_SUCCESS: 'UPDATE_CONTRIBUTION_SUCCESS',
    UPDATE_CONTRIBUTION_FAILURE: 'UPDATE_CONTRIBUTION_FAILURE',
    DELETE_CONTRIBUTION_REQUEST: 'DELETE_CONTRIBUTION_REQUEST',
    DELETE_CONTRIBUTION_SUCCESS: 'DELETE_CONTRIBUTION_SUCCESS',
    DELETE_CONTRIBUTION_FAILURE: 'DELETE_CONTRIBUTION_FAILURE',
    ADD_COMMENT_REQUEST: 'ADD_COMMENT_REQUEST',
    ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
    ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
    GET_COMMENT_REQUEST: 'GET_COMMENT_REQUEST',
    GET_COMMENT_SUCCESS: 'GET_COMMENT_SUCCESS',
    GET_COMMENT_FAILURE: 'GET_COMMENT_FAILURE',
    GET_STATISTIC_REQUEST: 'GET_STATISTIC_REQUEST',
    GET_STATISTIC_SUCCESS: 'GET_STATISTIC_SUCCESS',
    GET_STATISTIC_FAILURE: 'GET_STATISTIC_FAILURE',
}

export const facultyConstants = {
    GET_FACULTY_REQUEST: 'GET_FACULTY_REQUEST',
    GET_FACULTY_SUCCESS: 'GET_FACULTY_SUCCESS',
    GET_FACULTY_FAILURE: 'GET_FACULTY_FAILURE'
}

export const termConstants = {
    GET_TERMS_REQUEST: 'GET_TERMS_REQUEST',
    GET_TERMS_SUCCESS: 'GET_TERMS_SUCCESS',
    GET_TERMS_FAILURE: 'GET_TERMS_FAILURE',
}

