export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userConstants = {

}

export const contributionConstants = {
    GET_ALL_CONTRIBUTION_REQUEST: 'GET_ALL_CONTRIBUTION_REQUEST',
    GET_ALL_CONTRIBUTION_SUCCESS: 'GET_ALL_CONTRIBUTION_SUCCESS',
    GET_ALL_CONTRIBUTION_FAILURE: 'GET_ALL_CONTRIBUTION_FAILURE',
    GET_PUBLIC_CONTRIBUTION_REQUEST: 'GET_PUBLIC_CONTRIBUTION_REQUEST',
    GET_PUBLIC_CONTRIBUTION_SUCCESS: 'GET_PUBLIC_CONTRIBUTION_SUCCESS',
    GET_PUBLIC_CONTRIBUTION_FAILURE: 'GET_PUBLIC_CONTRIBUTION_FAILURE',
    GET_CONTRIBUTION_BY_FACULTY_REQUEST: 'GET_CONTRIBUTION_BY_FACULTY_REQUEST',
    GET_CONTRIBUTION_BY_FACULTY_SUCCESS: 'GET_CONTRIBUTION_BY_FACULTY_SUCCESS',
    GET_CONTRIBUTION_BY_FACULTY_FAILURE: 'GET_CONTRIBUTION_BY_FACULTY_FAILURE',
    PUBLISH_CONTRIBUTION_REQUEST: 'PUBLISH_CONTRIBUTION_REQUEST',
    PUBLISH_CONTRIBUTION_SUCCESS: 'PUBLISH_CONTRIBUTION_SUCCESS',
    PUBLISH_CONTRIBUTION_FAILURE: 'PUBLISH_CONTRIBUTION_FAILURE',
    ADD_CONTRIBUTION_REQUEST: 'ADD_CONTRIBUTION_REQUEST',
    ADD_CONTRIBUTION_SUCCESS: 'ADD_CONTRIBUTION_SUCCESS',
    ADD_CONTRIBUTION_FAILURE: 'ADD_CONTRIBUTION_FAILURE',
    UPDATE_CONTRIBUTION_REQUEST: 'UPDATE_CONTRIBUTION_REQUEST',
    UPDATE_CONTRIBUTION_SUCCESS: 'UPDATE_CONTRIBUTION_SUCCESS',
    UPDATE_CONTRIBUTION_FAILURE: 'UPDATE_CONTRIBUTION_FAILURE',
    DELETE_CONTRIBUTION_REQUEST: 'DELETE_CONTRIBUTION_REQUEST',
    DELETE_CONTRIBUTION_SUCCESS: 'DELETE_CONTRIBUTION_SUCCESS',
    DELETE_CONTRIBUTION_FAILURE: 'DELETE_CONTRIBUTION_FAILURE',
}